server:
  servlet:
    context-path:
  port: ${PORT:9004}

spring:
  datasource:
    url: jdbc:postgresql://cf5l5s63lru77b.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/ddn5clq89ro0bj
    username: u99eamhv0s1b4j
    password: p9f500aff753f4787b5fc8da87745c4d5aa8414d857e20724e31bc127aa858ce0
    driver-class-name: org.postgresql.Driver
  servlet:
    tomcat:
      initial-size: 2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL:true}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false
